name: Generate File Hashes

on:
  push:

jobs:
  generate_hashes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate SHA256 checksums
        uses: zgosalvez/checksum-action@v1 # Use the latest version
        with:
          pattern: "**/*.*" # Example: generate hashes for all .js files
          suffix: .sha256 # Appends .sha256 to the generated checksum file name

      - name: Commit checksum files (optional)
        uses: stefanzweifel/git-auto-commit-action@v5 # Use the latest version
        with:
          commit_message: "Add/Update file checksums"
          file_pattern: "*.sha256" # Commit only the generated checksum files
